apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: postgres