apiVersion: v1
kind: Secret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
metadata:
  name: postgres-secret
  labels:
    app: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "0"